### ISSUE TITLE
out of gpu memroy

### ISSUE THREAD

**Issue by mengce97** [thodan/sixd_toolkit#10]
when i run calc_gt_stats.py to get the scene_gt_stats of delta = 15,
the gpu memory will run out during the running,
how can i solve the problem?
Thank u for your reply!

**Comment by kaihsiangL** [comment]
@mengce97 I encountered another problem related to the virtual memory of the system. (but my gpu memory usage looks fine.) I wonder if our problems are related. 
1. When I run tools/eval_calc_error.py, virtual memory exploded when running and the process will crash. 
2. When I enabled visualization of the rendering of images, many windows were created but didn't close automatically. (The "window.close()" in pysixd/renderer.py doesn't work.)

system: Ubuntu 16.04 or 18.04
glumpy version: 1.1.0
numpy version: 1.16.4

**Comment by mengce97** [comment]
> @mengce97 I encountered another problem related to the virtual memory of the system. (but my gpu memory usage looks fine.) I wonder if our problems are related.
> 
> 1. When I run tools/eval_calc_error.py, virtual memory exploded when running and the process will crash.
> 2. When I enabled visualization of the rendering of images, many windows were created but didn't close automatically. (The "window.close()" in pysixd/renderer.py doesn't work.)
> 
> system: Ubuntu 16.04 or 18.04
> glumpy version: 1.1.0
> numpy version: 1.16.4

I solved the problem by calculating eval_calc_error one by one.You can also download the data from the author's website

**Comment by kaihsiangL** [comment]
@mengce97 
Thank you for sharing your solution.
I just found that the framecount parameter in app.run() will limit the number of windows the program opens.
The program will close all windows after reaching the given number of framecount.
Maybe this method works for you too.

**Comment by thodan** [comment]
Please switch to the BOP Toolkit (https://github.com/thodan/bop_toolkit). This memory issue is resolved there.
