### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.sixd'

### ISSUE THREAD

**Issue by capslocknanda** [thodan/sixd_toolkit#14]
I got this error.
(tf_gpu) D:\ssd-6d-master\ssd-6d-master>python run.py -/sixd/tejani/, -1, -10, -/weights_pretrained/tejani/tejani_obj_01.pb, -0.5, -3, -3
Traceback (most recent call last):
  File "run.py", line 28, in <module>
    from utils.sixd import load_sixd
ModuleNotFoundError: No module named 'utils.sixd'

**Comment by thodan** [comment]
This is not an issue of the SIXD Toolkit. Please consult https://github.com/wadimkehl/ssd-6d. I guess you need to run the script directly from the "ssd-6d" folder.
