### ISSUE TITLE
All return values are 0

### ISSUE THREAD

**Issue by r-9li** [thodan/sixd_toolkit#15]
https://github.com/thodan/sixd_toolkit/blob/96bb268e1fb5ebd82ca1b8d352e3263561ba6f5c/pysixd/renderer.py#
The return array is filled with zeros

**Comment by wendaizhou** [comment]
I have the same question with render..

**Comment by thodan** [comment]
SIXD Toolkit is no longer maintained. It was replaced by the BOP Toolkit (https://github.com/thodan/bop_toolkit) which contains all of the functionality of SIXD Toolkit and more.
