### ISSUE TITLE
Error: Unknown machine!

### ISSUE THREAD

**Issue by andersgb1** [thodan/sixd_toolkit#5]
The evaluation scripts do not work out of the box. I just ran my detector and produced the necessary YAML files for one of the datasets and tried to run **eval_calc_errors.py**, which immediately resulted in the error in the title, which seems to be issued from the file **machine.py**.

**Comment by thodan** [comment]
Thanks for the notice. The problem has been resolved -- I have removed the file machine.py, which was not necessary (it was there to make work on multiple machines easier).

**Comment by andersgb1** [comment]
Great, works on my side - however, I still need to set the parameter **common_base_path** inside **dataset_params.py**, so this information is in my view missing in the main README.

**Comment by thodan** [comment]
Ok, thanks for the remark. I have added the info the README file.
