### ISSUE TITLE
Script eval_loc.py does not work for partial results

### ISSUE THREAD

**Issue by andersgb1** [thodan/sixd_toolkit#6]
There is a discrepancy between the tolerance of the two main scripts **eval_calc_results.py** and **eval_loc.py** towards partial results.

Specifically, it is possible to run **eval_calc_results.py** to produce the **errors\*.yml** files for a dataset although I haven't run my algorithm on all scenes, but when I start the **eval_calc_results.py** on the generated **eval** subfolder, it breaks with a message like the following:
```bash
--- Processing: output, doumanoglou, vsd
Traceback (most recent call last):
  File "tools/eval_loc.py", line 332, in <module>
    main()
  File "tools/eval_loc.py", line 273, in main
    errs = inout.load_errors(scene_errs_path)
  File "/path/to/sixd_toolkit/pysixd/inout.py", line 158, in load_errors
    with open(path, 'r') as f:
IOError: [Errno 2] No such file or directory: '/path/to/eval/output_doumanoglou/error=vsd_ntop=1_delta=15_tau=20_cost=step/errors_02.yml'
```

It would be very convenient if the toolkit allowed evaluating partial results to avoid having to wait hours or even days to get an indication of the performance.

**Comment by andersgb1** [comment]
It seems that this can be resolved by inserting a check for file existence just before this line: https://github.com/thodan/sixd_toolkit/blob/f7398086621f70181137a8bcd3e427ad82247535/tools/eval_loc.py#L273

**Comment by thodan** [comment]
I have added switch require_all_errors (in eval_loc.py). If set to True (default), pre-calculated errors for all scenes are required, otherwise an exception is raised. If set to False, the script evaluates only scenes for which the pre-calculated errors are available.

**Comment by andersgb1** [comment]
Very nice - it works on my side. It could be an advantage for others to also have this info in the readme, but that's a minor thing...

**Comment by thodan** [comment]
Thanks. An explanation is provided if the exception is raised -- I think that should be sufficient.

**Comment by andersgb1** [comment]
Agree.
