### ISSUE TITLE
Expected outcomes of running eval_loc.py on sample results

### ISSUE THREAD

**Issue by XinkeAE** [thodan/sixd_toolkit#8]
Thank you so much for providing the sixd_toolkit to the community; it is well written and easy to use; I found it super helpful. 

Recently I was running some sanity check on your code with the sample data you provided. The code was pulled down from your github repo (https://github.com/thodan/sixd_toolkit/). And the data is downloaded from 
http://ptak.felk.cvut.cz/6DB/public/sixd_results/

I think if I run everything correctly, I should be able to generate the numbers your showed in the WACV 2017 paper on TLess dataset. However, I got different results, while using the default setting in your code:

--- Processing: hodan-iros15-forwacv17, tless, vsd

GT count:           69552
Target count:       49805
TP count:           34347
Total recall:       0.6896
Mean object recall: 0.6886
Mean scene recall:  0.7003
Object recalls:
1: 0.786, 2: 0.756, 3: 0.884, 4: 0.785, 5: 0.716, 6: 0.771, 7: 0.556, 8: 0.546, 9: 0.813, 10: 0.787, 11: 0.663, 12: 0.733, 13: 0.389, 14: 0.490, 15: 0.699, 16: 0.856, 17: 0.863, 18: 0.875, 19: 0.586, 20: 0.333, 21: 0.601, 22: 0.548, 23: 0.682, 24: 0.582, 25: 0.718, 26: 0.730, 27: 0.549, 28: 0.701, 29: 0.792, 30: 0.866
Scene recalls:
1: 0.848, 2: 0.818, 3: 0.614, 4: 0.805, 5: 0.827, 6: 0.721, 7: 0.759, 8: 0.526, 9: 0.855, 10: 0.456, 11: 0.681, 12: 0.817, 13: 0.661, 14: 0.588, 15: 0.578, 16: 0.650, 17: 0.762, 18: 0.640, 19: 0.736, 20: 0.665

Could you please let me know if I ran your code correctly.

Thank you!

**Comment by thodan** [comment]
This issue has been resolved in private conversation with Xinke. Here is the explanation:

The task in the BOP paper [1] and the T-LESS paper [2] is different. In [1], the task is "6D localization of a single instance of a single object", and in [2] the task is "6D localization of multiple instances of multiple objects". The first is "easier" and thus the recall rate for this task is expected to be higher. See section 2.1 in [1] for more details.

[1] Hodan et al., BOP: Benchmark for 6D Object Pose Estimation, ECCV 2018
[2] Hodan et al., T-LESS: An RGB-D Dataset for 6D Pose Estimation of Texture-less Objects, WACV 2017
